# Generated by Django 5.2.5 on 2025-09-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_failedloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedloginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
