# Generated by Django 5.2.5 on 2025-09-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='passkey',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
