# Generated by Django 5.2.5 on 2025-09-18 02:10

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='passkey',
            field=models.CharField(default=chat.models.generate_passkey, max_length=6),
        ),
    ]
