# Generated by Django 5.2.5 on 2025-09-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_systemsettings_site_name_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parsed_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
