# Generated by Django 5.2.5 on 2025-09-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auditlog_ip_address_auditlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_disable_inactive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_role',
            field=models.CharField(default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='log_downloads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_login_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='retention_days',
            field=models.IntegerField(default=30),
        ),
    ]
